/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.documentnode.minilog;

public class Example {

  private static final Logger log = Logger.create(Example.class);

  public static void main(String[] args) {
    log.info("Hello World");
  }
}
